# Generated by Django 4.1 on 2022-08-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_minimumage_lego_minimum_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lego',
            old_name='description',
            new_name='availability',
        ),
    ]
