# Generated by Django 4.1 on 2022-08-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='lego',
            name='collections',
            field=models.ManyToManyField(to='main_app.collection'),
        ),
    ]
