# Generated by Django 4.1 on 2022-08-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_lego_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lego',
            name='availability',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Backorder'), ('O', 'Out of Stock'), ('R', 'Retired')], default='A', max_length=1),
        ),
    ]
