# Generated by Django 4.1 on 2022-08-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_figure_accessories_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='accessories',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
