# Generated by Django 4.1 on 2022-08-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_figure_accessories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Figure',
            new_name='Minifig',
        ),
    ]
